// Gradle build file
// CSCI 205 - Software Engineering and Design
// Bucknell University
// Author - B. King / L. Romano / C. Kuhn
// Update Log
// 2022-Fall - added javamodularity, updated versions of javafxplugin
// 2023-Spring - Modified testLogging events
// 2025-Spring - Updated to prepare for some deprecation
// 2025-Fall - Updated for Gradle 9 and updated module system
// 2026-Spring - Updated for Gradle 10 and updated module system
// 2026-Spring - Added support for *theoretically* all PCs

plugins {
    id 'java'
    id 'application'
    id 'idea'
}


group = "org.five_nights_at_dana"
version = '0.0.1-SNAPSHOT'

repositories { mavenCentral() }
java { modularity.inferModulePath = true }
run { standardInput = System.in }

test {
    useJUnitPlatform()
    testLogging { events "passed", "skipped", "failed", "standard_out", "standard_error" }
}

def os = System.getProperty("os.name").toLowerCase()
def arch = System.getProperty("os.arch").toLowerCase()

def platform

if (os.contains("win")) {
    platform = "win"
} else if (os.contains("linux")) {
    if (arch.contains("aarch64") || arch.contains("arm")) platform = "linux-aarch64"
    else platform = "linux"
} else if (os.contains("mac")) {
    if (arch.contains("aarch64") || arch.contains("arm")) platform = "mac-aarch64"
    else platform = "mac"
} else throw new GradleException("Unsupported OS/arch: $os / $arch")

println "Detected JavaFX platform: $platform"

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.0'

    implementation "org.openjfx:javafx-controls:21.0.2:$platform"
    implementation "org.openjfx:javafx-fxml:21.0.2:$platform"
    implementation "org.openjfx:javafx-base:21.0.2:$platform"
    implementation "org.openjfx:javafx-graphics:21.0.2:$platform"
    implementation "org.openjfx:javafx-media:21.0.2:$platform"
}

application {
    mainModule.set("csci205_final_project")
//    mainClass.set("org.five_nights_at_dana.DanaEngineering")
    mainClass.set("org.five_nights_at_dana.AI.MVP")
}
